//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseMasterPolEntities : DbContext
    {
        private static DatabaseMasterPolEntities _context;
        public DatabaseMasterPolEntities()
            : base("name=DatabaseMasterPolEntities")
        {
        }
        
        public static DatabaseMasterPolEntities GetContext()
        {
            if(_context == null)
            {
                _context = new DatabaseMasterPolEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<MaterialTypeImport> MaterialTypeImport { get; set; }
        public virtual DbSet<NameArea> NameArea { get; set; }
        public virtual DbSet<NameCity> NameCity { get; set; }
        public virtual DbSet<NameDirector> NameDirector { get; set; }
        public virtual DbSet<NameStreet> NameStreet { get; set; }
        public virtual DbSet<NumberIndex> NumberIndex { get; set; }
        public virtual DbSet<PartnerImport> PartnerImport { get; set; }
        public virtual DbSet<PartnerProductImport> PartnerProductImport { get; set; }
        public virtual DbSet<ProductImport> ProductImport { get; set; }
        public virtual DbSet<ProductTypeImport> ProductTypeImport { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypePartner> TypePartner { get; set; }
    }
}
