//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metod.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.PartnerImport = new HashSet<PartnerImport>();
        }
    
        public int Id { get; set; }
        public int IdIndex { get; set; }
        public int IdArea { get; set; }
        public int IdCity { get; set; }
        public int IdStreet { get; set; }
        public int Home { get; set; }
    
        public virtual NameArea NameArea { get; set; }
        public virtual NameCity NameCity { get; set; }
        public virtual NameStreet NameStreet { get; set; }
        public virtual NumberIndex NumberIndex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerImport> PartnerImport { get; set; }
    }
}
