//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metod.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductImport
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdNamePartner { get; set; }
        public int QuantityProduct { get; set; }
        public System.DateTime DateSale { get; set; }
    
        public virtual ProductImport ProductImport { get; set; }
    }
}
